### GET ALL
GET http://localhost:3000/api/articles
Content-Type: application/json
Accept: application/json

### CREATE
POST http://localhost:3000/api/articles
Content-Type: application/json
Accept: application/json

{
  "title": "Udinus Jago",
  "description": "WOahh bisa banjir ternyata hehehe",
  "content": "hahahahha mps",
  "date": "2023-1-30",
  "author": "KOrie ",
  "location": "Semarang Tengah"
}


### UPDATE BY ID
PUT http://localhost:3000/api/articles/10
Content-Type: application/json
Accept: application/json

{
  "title": "JamalJgowoi ",
  "description": "WOahh bisa banjir ahahhaa",
  "content": "hahahahhdssa mps",
  "date": "2024-12-30",
  "author": "JAMAL",
  "location": "Semarang"
}

### DELETE BY ID
DELETE http://localhost:3000/api/articles/13
Content-Type: application/json
Accept: application/json